[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle authentication callbacks
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/next_renderer"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_renderer"
  status = 200 